/**
 * Canonical control library for the MOCK RCM demo.
 *
 * Language is bank ITGC / SOX, rewritten from public-domain control families
 * (NIST SP 800-53, FISCAM ITGCs, FDIC RMS IT examination topics). Text is not
 * a copy of any institution's RCM and is not a substitute for those catalogs.
 *
 * Institution: Wrenbridge Community Bank, N.A. — fictional. Checked against
 * the FDIC BankFind API (NAME:"Wrenbridge") on 2026-09-15: 0 institutions.
 */

export interface CanonicalControl {
  canonicalId: string;
  displayId: string;
  nistFamily: string;
  catalog: "NIST 800-53" | "FISCAM ITGC" | "FDIC RMS";
  title: string;
  description: string;
  owner: string;
  frequency: string;
  riskIds: string[];
  status: "active" | "withdrawn";
  tested: boolean;
  lastReviewedOn: string;
  sourceModifiedOn: string;
  issueId: string | null;
  issueStatus: string | null;
}

export const DIRECTORY = [
  { name: "Priya Nandakumar", title: "CISO", email: "priya.nandakumar@wrenbridge.example" },
  { name: "Marcus Hale", title: "IT Operations Manager", email: "marcus.hale@wrenbridge.example" },
  { name: "Elena Voss", title: "Internal Audit Manager", email: "elena.voss@wrenbridge.example" },
  { name: "David Chen", title: "SOX PMO Lead", email: "david.chen@wrenbridge.example" },
  { name: "Ruth Okonkwo", title: "Core Banking Operations", email: "ruth.okonkwo@wrenbridge.example" },
  { name: "Tom Alvarez", title: "Network Engineering", email: "tom.alvarez@wrenbridge.example" },
  { name: "Hannah Briggs", title: "Information Security", email: "hannah.briggs@wrenbridge.example" },
  { name: "Wei Zhang", title: "Application Development", email: "wei.zhang@wrenbridge.example" },
  { name: "Sofia Rahman", title: "Business Continuity", email: "sofia.rahman@wrenbridge.example" },
  { name: "James Whitaker", title: "Facilities", email: "james.whitaker@wrenbridge.example" },
  { name: "Nora Patel", title: "Vendor Management", email: "nora.patel@wrenbridge.example" },
  { name: "Chris Molina", title: "GL Accounting", email: "chris.molina@wrenbridge.example" },
] as const;

export const RISKS = [
  { riskId: "RISK-ACC-01", title: "Unauthorized access to core deposit systems", owner: "Priya Nandakumar" },
  { riskId: "RISK-CHG-01", title: "Uncontrolled change to production core", owner: "Marcus Hale" },
  { riskId: "RISK-SOD-01", title: "Incompatible duties in note and GL posting", owner: "Chris Molina" },
  { riskId: "RISK-OPS-01", title: "Failed batch or backup of core processing", owner: "Ruth Okonkwo" },
  { riskId: "RISK-VEN-01", title: "Core processor or fintech vendor failure", owner: "Nora Patel" },
  { riskId: "RISK-BCP-01", title: "Inability to resume deposit processing", owner: "Sofia Rahman" },
  { riskId: "RISK-PHY-01", title: "Unauthorized physical access to the computer room", owner: "James Whitaker" },
  { riskId: "RISK-LOG-01", title: "Security events not reviewed in time to act", owner: "Hannah Briggs" },
  { riskId: "RISK-ENC-01", title: "Cleartext wire or ACH file in transit or at rest", owner: "Tom Alvarez" },
  { riskId: "RISK-VUL-01", title: "Unpatched infrastructure exposed to known defects", owner: "Hannah Briggs" },
  { riskId: "RISK-IR-01", title: "Security incident not contained or reported", owner: "Priya Nandakumar" },
  { riskId: "RISK-HR-01", title: "Access retained after employee departure", owner: "Elena Voss" },
] as const;

export const CANONICAL_CONTROLS: CanonicalControl[] = [
  {
    canonicalId: "canon-ac-01",
    displayId: "ITGC-AC-01",
    nistFamily: "AC-2 Account Management",
    catalog: "NIST 800-53",
    title: "Joiner-mover-leaver for core and network IDs",
    description:
      "New core-banking, FedLine, and Active Directory IDs are requested through the access ticket, approved by the employee's manager and the application owner, and provisioned by IT Operations. Movers are recertified within five business days of the role change. Leavers are disabled the same day HR marks the last day.",
    owner: "Ruth Okonkwo",
    frequency: "Daily",
    riskIds: ["RISK-ACC-01", "RISK-HR-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-03-12",
    sourceModifiedOn: "2026-03-12",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-ac-02",
    displayId: "ITGC-AC-02",
    nistFamily: "AC-2 / AC-6 Privileged accounts",
    catalog: "NIST 800-53",
    title: "Quarterly recertification of privileged core IDs",
    description:
      "Application owners recertify every privileged ID on the core, SWIFT gateway, and domain admin groups each calendar quarter. IDs not recertified by the due date are disabled by IT Operations the next business day.",
    owner: "Elena Voss",
    frequency: "Quarterly",
    riskIds: ["RISK-ACC-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-02-20",
    sourceModifiedOn: "2026-02-20",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-ac-03",
    displayId: "ITGC-AC-03",
    nistFamily: "AC-5 Separation of Duties",
    catalog: "FISCAM ITGC",
    title: "Segregation of duties: note origination vs GL posting",
    description:
      "No user may both originate a commercial note in the core and post the related general-ledger entry. The SOD matrix is reviewed when roles change and at least annually. Exceptions require CFO written approval and a compensating review.",
    owner: "Chris Molina",
    frequency: "Annual",
    riskIds: ["RISK-SOD-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-01-18",
    sourceModifiedOn: "2026-01-18",
    issueId: "ISS-118",
    issueStatus: "open",
  },
  {
    canonicalId: "canon-ac-04",
    displayId: "ITGC-AC-04",
    nistFamily: "AC-6 Least Privilege",
    catalog: "NIST 800-53",
    title: "Privileged access on FedLine and core is named and logged",
    description:
      "Shared or generic administrator IDs are prohibited on FedLine, the core, and the wire room workstation. Each privileged session is logged and reviewed weekly by Information Security.",
    owner: "Hannah Briggs",
    frequency: "Weekly",
    riskIds: ["RISK-ACC-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-04-02",
    sourceModifiedOn: "2026-04-02",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-ac-05",
    displayId: "ITGC-AC-05",
    nistFamily: "AC-7 Unsuccessful Logon Attempts",
    catalog: "NIST 800-53",
    title: "Lockout after failed logons on employee SSO and digital banking admin",
    description:
      "Employee SSO and the digital-banking administration console lock an ID after five consecutive failed logons. Unlock requires a service desk ticket and manager confirmation.",
    owner: "Tom Alvarez",
    frequency: "Continuous",
    riskIds: ["RISK-ACC-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-03-01",
    sourceModifiedOn: "2026-03-01",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-ia-01",
    displayId: "ITGC-IA-01",
    nistFamily: "IA-2 Identification and Authentication",
    catalog: "NIST 800-53",
    title: "MFA for remote access and privileged core sessions",
    description:
      "Remote VPN, cloud admin, and any privileged core session require phishing-resistant multi-factor authentication. Emergency break-glass IDs are stored with dual control and logged.",
    owner: "Priya Nandakumar",
    frequency: "Continuous",
    riskIds: ["RISK-ACC-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-04-10",
    sourceModifiedOn: "2026-04-10",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-ia-02",
    displayId: "ITGC-IA-02",
    nistFamily: "IA-5 Authenticator Management",
    catalog: "NIST 800-53",
    title: "Authenticator issuance and reset",
    description:
      "Hardware tokens and password resets for core and FedLine are issued only after in-person or video identity verification against HR records. Default passwords are changed before the ID is activated.",
    owner: "Marcus Hale",
    frequency: "Daily",
    riskIds: ["RISK-ACC-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-02-08",
    sourceModifiedOn: "2026-02-08",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-au-01",
    displayId: "ITGC-AU-01",
    nistFamily: "AU-2 Event Logging",
    catalog: "NIST 800-53",
    title: "Security and core application logging enabled",
    description:
      "Logon, privileged commands, and parameter changes on the core, Active Directory, and firewalls are logged and retained for 18 months. Logging cannot be disabled without a change ticket.",
    owner: "Hannah Briggs",
    frequency: "Continuous",
    riskIds: ["RISK-LOG-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-03-22",
    sourceModifiedOn: "2026-03-22",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-au-02",
    displayId: "ITGC-AU-02",
    nistFamily: "AU-6 Audit Record Review",
    catalog: "NIST 800-53",
    title: "Weekly SIEM review of privileged and failed-access events",
    description:
      "Information Security reviews the SIEM dashboard of privileged use and failed access each week, documents the review, and opens an incident ticket for unexplained activity within one business day.",
    owner: "Hannah Briggs",
    frequency: "Weekly",
    riskIds: ["RISK-LOG-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-04-15",
    sourceModifiedOn: "2026-04-15",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-cm-01",
    displayId: "ITGC-CM-01",
    nistFamily: "CM-3 Configuration Change Control",
    catalog: "FISCAM ITGC",
    title: "Production changes to core and interfaces require a ticket",
    description:
      "Every production change to the core, ACH/wire interfaces, and general ledger feed requires a change ticket, test evidence, and approval by IT Operations and the application owner before migration. Emergency changes are retro-approved within two business days.",
    owner: "Marcus Hale",
    frequency: "Quarterly",
    riskIds: ["RISK-CHG-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-03-28",
    sourceModifiedOn: "2026-03-28",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-cm-02",
    displayId: "ITGC-CM-02",
    nistFamily: "CM-6 Configuration Settings",
    catalog: "NIST 800-53",
    title: "Hardening baselines for servers that host the core",
    description:
      "Servers that host the core and its database are built from a documented hardening baseline. Deviations are tracked as exceptions with an expiration date and compensating control.",
    owner: "Tom Alvarez",
    frequency: "Quarterly",
    riskIds: ["RISK-CHG-01", "RISK-VUL-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-02-14",
    sourceModifiedOn: "2026-02-14",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-cm-03",
    displayId: "ITGC-CM-03",
    nistFamily: "CM-2 Baseline Configuration",
    catalog: "NIST 800-53",
    title: "Baseline inventory of in-scope SOX applications",
    description:
      "The SOX PMO maintains an inventory of in-scope applications, data flows, and owners. Additions and retirements are approved in the quarterly scoping meeting.",
    owner: "David Chen",
    frequency: "Quarterly",
    riskIds: ["RISK-CHG-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-04-01",
    sourceModifiedOn: "2026-04-01",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-cp-01",
    displayId: "ITGC-CP-01",
    nistFamily: "CP-2 Contingency Plan",
    catalog: "FDIC RMS",
    title: "Contingency plan for core deposit processing",
    description:
      "The bank maintains a documented contingency plan covering core deposit processing, ATM/debit authorization, and FedLine. Recovery time for deposit posting is 4 hours; recovery point is the last successful batch.",
    owner: "Sofia Rahman",
    frequency: "Annual",
    riskIds: ["RISK-BCP-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-01-30",
    sourceModifiedOn: "2026-01-30",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-cp-02",
    displayId: "ITGC-CP-02",
    nistFamily: "CP-4 Contingency Plan Testing",
    catalog: "FDIC RMS",
    title: "Annual disaster-recovery test of core processing",
    description:
      "IT Operations and Business Continuity run an annual disaster-recovery test that fails the core to the alternate site, posts a sample deposit file, and records actual recovery time against the 4-hour objective. Exceptions are logged as issues.",
    owner: "Sofia Rahman",
    frequency: "Annual",
    riskIds: ["RISK-BCP-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2024-05-01",
    sourceModifiedOn: "2024-05-12",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-cp-03",
    displayId: "ITGC-CP-03",
    nistFamily: "CP-9 Information System Backup",
    catalog: "FISCAM ITGC",
    title: "Nightly backup of core and general ledger",
    description:
      "Nightly backups of the core database and the general ledger are completed, verified by a restore-sample monthly, and stored offsite. Failed backups page IT Operations before 7 a.m.",
    owner: "Marcus Hale",
    frequency: "Daily",
    riskIds: ["RISK-OPS-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-04-05",
    sourceModifiedOn: "2026-04-05",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-pe-01",
    displayId: "ITGC-PE-01",
    nistFamily: "PE-3 Physical Access Control",
    catalog: "NIST 800-53",
    title: "Computer-room badge access and visitor log",
    description:
      "The computer room is restricted by badge. Access lists are recertified quarterly by Facilities and IT Operations. Visitors are escorted and logged. Terminated employees' badges are collected the last day.",
    owner: "James Whitaker",
    frequency: "Quarterly",
    riskIds: ["RISK-PHY-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-03-05",
    sourceModifiedOn: "2026-03-05",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-si-01",
    displayId: "ITGC-SI-01",
    nistFamily: "SI-4 System Monitoring",
    catalog: "NIST 800-53",
    title: "Malware and IDS alerting on bank workstations and servers",
    description:
      "Endpoint malware protection and network IDS cover all bank workstations and servers. Alerts are triaged by Information Security within four hours during business days.",
    owner: "Hannah Briggs",
    frequency: "Continuous",
    riskIds: ["RISK-VUL-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2025-11-02",
    sourceModifiedOn: "2025-11-02",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-ra-01",
    displayId: "ITGC-RA-01",
    nistFamily: "RA-5 Vulnerability Monitoring",
    catalog: "NIST 800-53",
    title: "Quarterly vulnerability scanning of in-scope infrastructure",
    description:
      "In-scope servers and network devices are scanned at least quarterly. Critical findings are patched or formally accepted within 30 days; high findings within 90 days.",
    owner: "Hannah Briggs",
    frequency: "Quarterly",
    riskIds: ["RISK-VUL-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-02-28",
    sourceModifiedOn: "2026-02-28",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-sc-01",
    displayId: "ITGC-SC-01",
    nistFamily: "SC-8 Transmission Confidentiality",
    catalog: "NIST 800-53",
    title: "Encryption in transit for ACH, wire, and core-processor files",
    description:
      "ACH, wire, and core-processor files leaving the bank are encrypted in transit (TLS 1.2 or higher). Plaintext FTP is prohibited.",
    owner: "Tom Alvarez",
    frequency: "Continuous",
    riskIds: ["RISK-ENC-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-03-18",
    sourceModifiedOn: "2026-03-18",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-sc-02",
    displayId: "ITGC-SC-02",
    nistFamily: "SC-28 Protection of Information at Rest",
    catalog: "NIST 800-53",
    title: "Encryption at rest for core database backups",
    description:
      "Core database backups are encrypted at rest with keys held in the bank's key-management process, split from the backup operators.",
    owner: "Marcus Hale",
    frequency: "Continuous",
    riskIds: ["RISK-ENC-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-03-18",
    sourceModifiedOn: "2026-03-18",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-sa-01",
    displayId: "ITGC-SA-01",
    nistFamily: "SA-9 External System Services",
    catalog: "FDIC RMS",
    title: "Oversight of the core processor and material fintechs",
    description:
      "Vendor Management reviews SOC reports, financials, and concentration risk for the core processor and material fintechs at least annually, with findings reported to the steering committee.",
    owner: "Nora Patel",
    frequency: "Annual",
    riskIds: ["RISK-VEN-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-01-22",
    sourceModifiedOn: "2026-01-22",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-ir-01",
    displayId: "ITGC-IR-01",
    nistFamily: "IR-4 / IR-6 Incident Handling and Reporting",
    catalog: "FDIC RMS",
    title: "Security incident handling and regulatory notification",
    description:
      "Confirmed security incidents are handled under the incident plan. Notification to the primary federal regulator and, when required, to customers follows the bank's incident-notification matrix.",
    owner: "Priya Nandakumar",
    frequency: "Event-driven",
    riskIds: ["RISK-IR-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-02-05",
    sourceModifiedOn: "2026-02-05",
    issueId: null,
    issueStatus: null,
  },
  {
    canonicalId: "canon-ps-01",
    displayId: "ITGC-PS-01",
    nistFamily: "PS-4 Personnel Termination",
    catalog: "NIST 800-53",
    title: "Same-day collection of tokens and badges on termination",
    description:
      "On an employee's last day, HR notifies IT Operations and Facilities. Hardware tokens, VPN certificates, and badges are collected or revoked the same day, and a termination checklist is filed.",
    owner: "Elena Voss",
    frequency: "Daily",
    riskIds: ["RISK-HR-01"],
    status: "active",
    tested: true,
    lastReviewedOn: "2026-03-09",
    sourceModifiedOn: "2026-03-09",
    issueId: null,
    issueStatus: null,
  },
];

export const TRIGGERS = [
  { name: "core_banking_conversion", date: "2025-03-15" },
  { name: "annual_it_examination", date: "2025-08-20" },
] as const;

/** Import as-of date is evidence on the file, never the wall clock. */
export const IMPORT_AS_OF = "2026-06-01";
